apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-cicd
  labels:
    app: cicd
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cicd
  template:
    metadata:
      labels:
        app: cicd
    spec:
      containers:
      - name: web-app
        image: nikhil1997/node-image:latest
        ports:
        - containerPort: 8080
      - name: redis-server
        image: redis:alpine3.18

